
export type KeyCategory = "core" | "auth" | "payments" | "ai" | "analytics" | "email" | "storage";

export const CATEGORIES: { id: KeyCategory; label: string; icon: string; description: string }[] = [
  { id: "core", label: "Core Services", icon: "⚙️", description: "Essential platform services." },
  { id: "auth", label: "Authentication", icon: "🛡️", description: "User sign-in and security." },
  { id: "payments", label: "Payments & Billing", icon: "💳", description: "Stripe and payment processing." },
  { id: "ai", label: "Artificial Intelligence", icon: "🤖", description: "OpenAI and other AI models." },
  { id: "analytics", label: "Analytics & Monitoring", icon: "📊", description: "Tracking and performance." },
  { id: "email", label: "Email Services", icon: "✉️", description: "Transactional and marketing emails." },
  { id: "storage", label: "Storage", icon: "📦", description: "File and data storage." },
];

export const KEY_SPECS = [
  {
    key: "VITE_SUPABASE_URL",
    label: "Supabase URL",
    scope: "client_public",
    envTarget: "both",
    category: "core",
    company: "Supabase",
    example: "https://[id].supabase.co",
    description: "The unique URL for your Supabase project.",
    required: true,
  },
  {
    key: "VITE_SUPABASE_ANON_KEY",
    label: "Supabase Anon Key",
    scope: "client_public",
    envTarget: "both",
    category: "core",
    company: "Supabase",
    description: "The public, anonymous key for client-side access to Supabase.",
    required: true,
  },
  {
    key: "VITE_STRIPE_PUBLISHABLE_KEY",
    label: "Stripe Publishable Key",
    scope: "client_public",
    envTarget: "both",
    category: "payments",
    company: "Stripe",
    example: "pk_test_...",
    description: "The publishable key for Stripe.js on the client-side.",
    required: true,
  },
  {
    key: "STRIPE_SECRET_KEY",
    label: "Stripe Secret Key",
    scope: "server_private",
    envTarget: "production",
    category: "payments",
    company: "Stripe",
    description: "The secret key for server-side Stripe operations (e.g., creating checkouts).",
    required: true,
  },
   {
    key: "STRIPE_WEBHOOK_SECRET",
    label: "Stripe Webhook Secret",
    scope: "server_private",
    envTarget: "production",
    category: "payments",
    company: "Stripe",
    description: "The secret for verifying incoming webhooks from Stripe.",
    required: true,
  },
  {
    key: "OPENAI_API_KEY",
    label: "OpenAI API Key",
    scope: "server_private",
    envTarget: "production",
    category: "ai",
    company: "OpenAI",
    description: "API key for accessing OpenAI models like GPT-4.",
    required: false,
  },
  {
    key: "RESEND_API_KEY",
    label: "Resend API Key",
    scope: "server_private",
    envTarget: "production",
    category: "email",
    company: "Resend",
    description: "API key for sending emails with Resend.",
    required: true,
  },
  {
    key: "VITE_CONFIG_LOCK",
    label: "Config Lock Flag",
    scope: "flag",
    envTarget: "both",
    category: "core",
    company: "Internal",
    description: "Set to '1' to lock the API Keys Manager from being edited.",
    required: false,
  },
];
